---
title: "rOpenGov"
subtitle: "10 years of R Packages for Open Governmental Data"
author: "Pyry Kantanen, Leo Lahti"
institute: "rOpenGov"
date: "2021/09/24 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: inverse, center, middle

# About rOpenGov

---

# Brief history

- Started in 2010
- Entry in Apps4Finland competition
- Core team: Leo Lahti, Markus Kainu, Joona Lehtomäki, Juuso Paananen

---

class: inverse, center, middle

# Definitions

---

class: center, middle

# What is Open Data?

> “Open means anyone can freely access, use, modify, and share for any purpose (subject, at most, to requirements that preserve provenance and openness).”


> “Open data and content can be freely used, modified, and shared by anyone for any purpose”<sup>1</sup>

.footnote[
[1] [Open Knowledge Foundation: Open Definition 2.1](https://opendefinition.org/od/2.1/en/)
]

---
class: center, middle

# What is Open Government Data?

>"Government data: is any data and information produced or commissioned by public bodies."<sup>1</sup>

Open Government Data: See above & See Open Data

.footnote[
[1] [Ubaldi, B. (2013), "Open Government Data: Towards Empirical Analysis of Open Government Data Initiatives", OECD Working Papers on Public Governance, No. 22, OECD Publishing, Paris, https://doi.org/10.1787/5k46bj4f03s7-en.](https://doi.org/10.1787/5k46bj4f03s7-en.)
]

---

# Examples of Open Government Data

OECD open governmental data analysis includes the following categories:
- business information (Chamber of Commerce information, official business)
- registers, patent and trademark information, public tender databases
- geographic information (address information, aerial photos, buildings, cadastral or land registry data, geodetic networks, hydrographical data, topographic information)
- legal information
- meteorological information (climate data, climate models, weather forecasts)
- social data (various types of statistics on economics, employment, health, population, public administration)
- transport information (traffic congestion, work on roads, public transport, vehicle registration)<sup>1</sup>

.footnote[
[1] Ubaldi, B. (2013) p. 6.
]

---

# What is already done?

.pull-left[
- [ ] business information
- [ ] registers
- [ ] patent and trademark information
- [ ] public tender databases
- [x] **geographic information**
  - geofi
  - regions
  - giscoR
  - helsinki
  - turku<sup>1</sup>
- [ ] legal information
- [x] **meteorological information**
  - fmi2
]

.pull-right[
- [x] **social data**
  - pxweb 
  - sotkanet
  - eurostat
  - hetu, sweidnumber
  - iotables
  - openthl<sup>1</sup>
  - *vipunen*<sup>2</sup>
- [x] **transport information** 
  - turku[1]
  - *digitransit*<sup>2</sup>
]

.footnote[
[1] Unreleased, currently under development

[2] Currently unmaintained
]

---
class: inverse, center, middle

# Another perspectives of open
## Open means transparent
## Open means participatory

---

# Open government, open society?

- Government: "Of the people, by the people, for the people"?<sup>1</sup>

--

- "Government that is wholly accountable and responsive to its citizens, and in which political decision-making is entirely transparent" (Karl Popper (2013) in *The Open Society and its enemies*, according to Pomerantz and Peek (2016))<sup>2</sup>

--

  - Inspiration to Open Society Foundations, which understands society as more than its government and its citizens<sup>2</sup>

.footnote[
[1] Lincoln, 1863

[2] Pomerantz, J. & Peek R. (2016). "Fifty shades of open", First Monday, Volume 21, Number 5 - 2 May 2016
https://firstmonday.org/ojs/index.php/fm/article/download/6360/5460, http://dx.doi.org/10.5210/fm.v21i5.6360
]

---

# Open means participatory

- "information about what the government is doing is meaningless without the **ability** for citizens to then **act on that information to exert influence on the government**"<sup>1</sup>

--

- Two crucial points:
  - **Ability to utilize information**: Not everyone should need to go through documentation for different APIs to be able to access it 
      - <u>This concerns us</u>
  - **Will to act**: Intrinsic motivation to make a change towards whichever goal the individual deems important
      - <u>This does not concern us</u>, as individual leanings or goals are not our concern?
      - However, generally speaking we want to encourage and empower people to act

.footnote[
[1] Pomerantz, J. & Peek R. (2016).
]

---

# Nods towards the fourth estate

Packages related to media:
- rsunlight - Interface to Sunlight Foundation APIs 
- RPublica - ProPublica API client
- pollstR - HuffPost Pollster API
- rtimes - New York Times APIs

---

# International (Non-Finnish) outlooks

Packages with Non-Finnish focus:
- rustfare - Russian Federation open welfare data
- ogdindiar - Data from Open Government Data Platform - India
- federalregister - U.S. Federal Register API
- mpg - Fuel economy data from FuelEconomy.gov
- usbroadband - Data from U.S. Broadband Map
- recalls - U.S. recall data from Food and Drug Administration (food and drug recalls), National Highway Traffic Safety Administration (car recalls), Consumer Product Safety Commission (product recalls)
- hansard - data from UK Parliament API

---

# Example r code

Install **helsinki** package from [Github](https://github.com/ropengov/helsinki):

```{r eval=FALSE, tidy=FALSE}
remotes::install_github("ropengov/helsinki")
```

--

You are recommended to use the [RStudio IDE](https://www.rstudio.com/products/rstudio/), but you do not have to.

- Create a new R Markdown document from the menu `File -> New File -> R Markdown -> From Template -> Ninja Presentation`;<sup>1</sup>

--

- Click the `Knit` button to compile it;

--

- or use the [RStudio Addin](https://rstudio.github.io/rstudioaddins/)<sup>2</sup> "Infinite Moon Reader" to live preview the slides (every time you update and save the Rmd document, the slides will be automatically reloaded in RStudio Viewer.

---
background-image: url(`r xaringan:::karl`)
background-position: 50% 50%
class: center, bottom, inverse

# You only live once!
